spring.application.name=REST_AlmacenLaboratorio

server.port=8080
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

server.servlet.context-path=/dbrestalmacenlaboratorio

#Conexio a MySQL, AJUSTAR SI TU BASE DE DATOS TIENE UN PUERTO DIFERENTE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/DBRESTALMACENLABORATORIO
spring.datasource.username=root
spring.datasource.password=root

