spring.application.name=REST_AlmacenLaboratorio

server.port=8080
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

server.servlet.context-path=/dbrestalmacenlaboratorio

#Conexio a MySQL, AJUSTAR SI TU BASE DE DATOS TIENE UN PUERTO DIFERENTE
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:54270;database=DBRESTALMACENLABORATORIO;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=012484260

